// services/apiHooks.js
import apiSlice from "./apiSlice";

// Export hooks generated by createApi
export const {
  useLoginMutation,
  useGetUserDataQuery,
  useCreateApplicationMutation,
  useCreateProjectMutation,
  useGetProjectListQuery,
  useUpdateUserMutation,
  useChangePasswordMutation,
  useSetDefaultMutation,
  useGetTestPlanListsQuery,
  useCreateSchedulerMutation,
  useDeleteSchedulerMutation,
  useGetTestPlanInformationQuery,
  useUpdateSchedulerMutation,
  useGetApplicationDetailsByIdQuery,
  useUpdateProjectDetailsByIdMutation,
  useDeleteProjectByIdMutation,
  useDeleteApplicationByIdMutation,
  useUpdateApplicationByIdMutation,
  useUploadFileChunkMutation,
  useRemoveAppFileMutation,
  useGetIntegrationQuery,
  useCreateIntegrationMutation,
  useUpdateIntegrationMutation,
  useDeleteIntegrationMutation,
  useDeleteProjectMutation,
  useGetRunsTestCaseListQuery,
  useCreateTestCaseRunMutation,
  useLazyGetTestPlanInformationQuery,
  useDeleteRunsListMutation,
  useCreateTestSuiteRunMutation,
  useCreateUserMutation,
  useDeleteUserDataMutation,
  useUpdateUserStatusApplicationMutation,
  useUpdateUserRoleApplicationMutation,
  useGetProjectListInfoQuery,
  useLazyGetProjectListQuery,
  useLazyGetApplicationDetailsByIdQuery,
  useLazyGetTestPlanListsQuery,
  useGetApplicationCountInfoMutation,
  useUploadProfileImageMutation,
  useDeleteProfileImageMutation,
  useLazyGetRunsTestCaseListQuery,
  useLazyGetUserDataQuery,
  useEmailNotificationMutation,
  useCreateGlobalVariableMutation,
  useLazyGetGlobalVariableQuery,
  useUpdateGlobalVariableMutation,
  useDeleteGlobalVariableMutation
} = apiSlice;

// invalidating
export const invalidateUserCache = () => apiSlice.util.invalidateTags(["User"]);
export const invalidateProjectCache = () =>
  apiSlice.util.invalidateTags(["Project"]);

// reseting Api Cache
export const resetApiCache = () => apiSlice.util.resetApiState();
