export const results = [
    {
      _id: "66e7e0a1237d17ee22a671c0",
      method: "Add Assertion",
      label: "Assertion Type",
      subMethod: [
        {
          _id: "66e7e0a1237d17ee22a671c1",
          method: "Element Is Present",
          isElementTarget: true,
          isOutputValue: false,
          isInputValue: false,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e7e0a1237d17ee22a671c2",
          method: "Element Is Not Present",
          isElementTarget: true,
          isOutputValue: false,
          isInputValue: false,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e7e0a1237d17ee22a671c3",
          method: "Element Is Visible",
          isElementTarget: true,
          isOutputValue: false,
          isInputValue: false,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e7e0a1237d17ee22a671c4",
          method: "Element Is Not Visible",
          isElementTarget: true,
          isInputValue: false,
          isOutputValue: false,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e7e0a1237d17ee22a671c5",
          method: "Element Is Clickable",
          isElementTarget: true,
          isOutputValue: false,
          isInputValue: false,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e7e0a1237d17ee22a671c6",
          method: "Element Is Not Clickable",
          isElementTarget: true,
          isOutputValue: false,
          isInputValue: false,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e7e0a1237d17ee22a671c7",
          method: "Element Matches Value",
          isElementTarget: true,
          isInputValue: false,
          isOutputValue: false,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e7e0a1237d17ee22a671c8",
          method: "Element Does Not Match Value",
          isElementTarget: true,
          isInputValue: false,
          isOutputValue: false,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e7e0a1237d17ee22a671c9",
          method: "Element Contains Value",
          isElementTarget: true,
          isInputValue: false,
          isOutputValue: false,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e7e0a1237d17ee22a671ca",
          method: "Element Does Not Contain Value",
          isElementTarget: true,
          isOutputValue: false,
          isInputValue: false,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e7e0a1237d17ee22a671cb",
          method: "Element Contains CSS Class",
          isElementTarget: true,
          isOutputValue: false,
          isDeleted: false,
          isInputValue: false,
          subMethod: [],
        },
        {
          _id: "66e7e0a1237d17ee22a671cc",
          method: "Element Does Not Contain CSS Class",
          isElementTarget: true,
          isOutputValue: false,
          isInputValue: false,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e7e0a1237d17ee22a671cd",
          method: "Element Contains Attribute",
          isElementTarget: true,
          isInputValue: false,
          isOutputValue: false,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e7e0a1237d17ee22a671ce",
          method: "Element Does Not Contain Attribute",
          isElementTarget: true,
          isOutputValue: false,
          isInputValue: false,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e7e0a1237d17ee22a671cf",
          method: "Count Child Elements",
          isElementTarget: true,
          isInputValue: false,
          isOutputValue: false,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e7e0a1237d17ee22a671d0",
          method: "Title Contains Value",
          isElementTarget: false,
          isInputValue: true,
          isOutputValue: false,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e7e0a1237d17ee22a671d1",
          method: "Title Does Not Contain Value",
          isElementTarget: false,
          isInputValue: true,
          isOutputValue: false,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e7e0a1237d17ee22a671d2",
          method: "URL Contains Value",
          isElementTarget: false,
          isInputValue: true,
          isOutputValue: false,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e7e0a1237d17ee22a671d3",
          method: "URL Does Not Contain Value",
          isElementTarget: false,
          isOutputValue: false,
          isInputValue: true,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e7e0a1237d17ee22a671d4",
          method: "Page Source Contains Value",
          isElementTarget: false,
          isOutputValue: false,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e7e0a1237d17ee22a671d5",
          method: "Page Source Does Not Contain Value",
          isElementTarget: false,
          isInputValue: true,
          isOutputValue: false,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e7e0a1237d17ee22a671d6",
          method: "Cookies Contain Value",
          isElementTarget: false,
          isOutputValue: false,
          isDeleted: false,
          isInputValue: true,
          subMethod: [],
        },
        {
          _id: "66e7e0a1237d17ee22a671d7",
          method: "Cookies Do Not Contain Value",
          isElementTarget: false,
          isOutputValue: false,
          isDeleted: false,
          isInputValue: true,
          subMethod: [],
        },
        {
          _id: "66e7e0a1237d17ee22a671d8",
          method: "Browser Logs Contain Value",
          isElementTarget: false,
          isOutputValue: false,
          isDeleted: false,
          isInputValue: true,
          subMethod: [],
        },
        {
          _id: "66e7e0a1237d17ee22a671d9",
          method: "Browser Logs Do Not Contain Value",
          isElementTarget: false,
          isOutputValue: false,
          isInputValue: true,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e7e0a1237d17ee22a671da",
          method: "Page Matches Screenshot",
          isElementTarget: false,
          isOutputValue: false,
          isInputValue: true,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e7e0a1237d17ee22a671db",
          method: "Full Page Matches Screenshot",
          isElementTarget: false,
          isOutputValue: false,
          isInputValue: true,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e7e0a1237d17ee22a671dc",
          method: "Element Matches Screenshot",
          isElementTarget: false,
          isOutputValue: false,
          isInputValue: false,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e7e0a1237d17ee22a671dd",
          method: "Variable Assertion",
          isDeleted: false,
          subMethod: [
            {
              _id: "66e7e0a1237d17ee22a671de",
              method: "Variable Matches Value",
              isElementTarget: false,
              isInputValue: true,
              isOutputValue: true,
              isDeleted: false,
            },
            {
              _id: "66e7e0a1237d17ee22a671df",
              method: "Variable Does Not Match Value",
              isElementTarget: false,
              isOutputValue: true,
              isInputValue: true,
              isDeleted: false,
            },
            {
              _id: "66e7e0a1237d17ee22a671e0",
              method: "Variable Contains Value",
              isElementTarget: false,
              isOutputValue: true,
              isInputValue: true,
              isDeleted: false,
            },
            {
              _id: "66e7e0a1237d17ee22a671e1",
              method: "Variable Does Not Contain Value",
              isElementTarget: false,
              isInputValue: true,
              isOutputValue: true,
              isDeleted: false,
            },
            {
              _id: "66e7e0a1237d17ee22a671e2",
              method: "Variable Starts With Value",
              isElementTarget: false,
              isInputValue: true,
              isOutputValue: true,
              isDeleted: false,
            },
            {
              _id: "66e7e0a1237d17ee22a671e3",
              method: "Variable Does Not Start With Value",
              isElementTarget: false,
              isInputValue: true,
              isOutputValue: true,
              isDeleted: false,
            },
            {
              _id: "66e7e0a1237d17ee22a671e4",
              method: "Variable Ends With Value",
              isElementTarget: false,
              isOutputValue: true,
              isInputValue: true,
              isDeleted: false,
            },
            {
              _id: "66e7e0a1237d17ee22a671e5",
              method: "Variable Does Not End With Value",
              isElementTarget: false,
              isOutputValue: true,
              isInputValue: true,
              isDeleted: false,
            },
            {
              _id: "66e7e0a1237d17ee22a671e6",
              method: "Variable Is Greater Than Value",
              isElementTarget: false,
              isInputValue: true,
              isOutputValue: true,
              isDeleted: false,
            },
            {
              _id: "66e7e0a1237d17ee22a671e7",
              method: "Variable Is Greater Than Or Equals Value",
              isElementTarget: false,
              isInputValue: true,
              isOutputValue: true,
              isDeleted: false,
            },
            {
              _id: "66e7e0a1237d17ee22a671e8",
              method: "Variable Is Less Than Value",
              isElementTarget: false,
              isInputValue: true,
              isOutputValue: true,
              isDeleted: false,
            },
            {
              _id: "66e7e0a1237d17ee22a671e9",
              method: "Variable Is Less Than Or Equals Value",
              isElementTarget: false,
              isOutputValue: true,
              isInputValue: true,
              isDeleted: false,
            },
            {
              _id: "66e7e0a1237d17ee22a671ea",
              method: "Variable Is Defined",
              isElementTarget: false,
              isOutputValue: false,
              isInputValue: true,
              isDeleted: false,
            },
            {
              _id: "66e7e0a1237d17ee22a671eb",
              method: "Variable Is Not Defined",
              isElementTarget: false,
              isOutputValue: false,
              isInputValue: true,
              isDeleted: false,
            },
            {
              _id: "66e7e0a1237d17ee22a671ec",
              method: "Variable Is Empty",
              isElementTarget: false,
              isInputValue: true,
              isOutputValue: false,
              isDeleted: false,
            },
            {
              _id: "66e7e0a1237d17ee22a671ed",
              method: "Variable Is Not Empty",
              isElementTarget: false,
              isOutputValue: false,
              isInputValue: true,
              isDeleted: false,
            },
            {
              _id: "66e7e0a1237d17ee22a671ee",
              method: "Variable Contains Numbers",
              isElementTarget: false,
              isInputValue: true,
              isOutputValue: false,
              isDeleted: false,
            },
            {
              _id: "66e7e0a1237d17ee22a671ef",
              method: "Variable Does Not Contain Numbers",
              isElementTarget: false,
              isInputValue: true,
              isOutputValue: false,
              isDeleted: false,
            },
          ],
        },
      ],
    },
    {
      _id: "66e7e6bdbd0427ce25e0b3fb",
      method: "Scroll",
      label: "Scroll Type",
      subMethod: [
        {
          _id: "66e7e6bdbd0427ce25e0b3fc",
          method: "Scroll down",
          isElementTarget: false,
          isInputValue: true,
          isOutputValue: false,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e7e6bdbd0427ce25e0b3fd",
          method: "Scroll up",
          isElementTarget: false,
          isInputValue: true,
          isOutputValue: false,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e7e6bdbd0427ce25e0b3fe",
          method: "Scroll left",
          isElementTarget: false,
          isOutputValue: false,
          isDeleted: false,
          isInputValue: true,
          subMethod: [],
        },
        {
          _id: "66e7e6bdbd0427ce25e0b3ff",
          method: "Scroll right",
          isElementTarget: false,
          isOutputValue: false,
          isDeleted: false,
          isInputValue: true,
          subMethod: [],
        },
        {
          _id: "66e7e6bdbd0427ce25e0b400",
          method: "Scroll to bottom",
          isElementTarget: false,
          isInputValue: true,
          isOutputValue: false,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e7e6bdbd0427ce25e0b401",
          method: "Scroll to top",
          isElementTarget: false,
          isOutputValue: false,
          isInputValue: true,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e7e6bdbd0427ce25e0b402",
          method: "Scroll to element",
          isElementTarget: false,
          isOutputValue: false,
          isInputValue: false,
          isDeleted: false,
          subMethod: [],
        },
      ],
    },
    {
      _id: "66e7e8caeca8ecf3a8249af5",
      method: "Print in Results",
      label: "Result Type",
      subMethod: [
        {
          _id: "66e7e8caeca8ecf3a8249af6",
          method: "Note",
          isElementTarget: false,
          isOutputValue: false,
          isInputValue: true,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e7e8caeca8ecf3a8249af7",
          method: "Current Title",
          isElementTarget: false,
          isOutputValue: false,
          isInputValue: false,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e7e8caeca8ecf3a8249af8",
          method: "Current URL",
          isElementTarget: false,
          isOutputValue: false,
          isDeleted: false,
          isInputValue: false,
          subMethod: [],
        },
        {
          _id: "66e7e8caeca8ecf3a8249af9",
          method: "Variable",
          isElementTarget: false,
          isOutputValue: false,
          isInputValue: true,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e7e8caeca8ecf3a8249afa",
          method: "All Variables",
          isElementTarget: false,
          isOutputValue: false,
          isInputValue: false,
          isDeleted: false,
          subMethod: [],
        },
      ],
    },
    {
      _id: "66e7f77ab8ec536409992de0",
      method: "Set Variable",
      label: "Variable Name",
      subMethod: [
        {
          _id: "66e7f77ab8ec536409992de1",
          method: "Set Value",
          isElementTarget: false,
          isInputValue: true,
          isOutputValue: true,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e7f77ab8ec536409992de2",
          method: "Set Password",
          isElementTarget: false,
          isOutputValue: true,
          isInputValue: true,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e7f77ab8ec536409992de3",
          method: "Random Number",
          isElementTarget: false,
          isOutputValue: true,
          isDeleted: false,
          isInputValue: true,
          subMethod: [],
        },
        {
          _id: "66e7f77ab8ec536409992de4",
          method: "Random String",
          isElementTarget: false,
          isOutputValue: true,
          isDeleted: false,
          isInputValue: true,
          subMethod: [],
        },
        {
          _id: "66e7f77ab8ec536409992de5",
          method: "Random Email",
          isElementTarget: false,
          isOutputValue: true,
          isInputValue: true,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e7f77ab8ec536409992de6",
          method: "Real Phone Number",
          isElementTarget: false,
          isOutputValue: true,
          isInputValue: true,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e7f77ab8ec536409992de7",
          method: "Timestamp",
          isElementTarget: false,
          isOutputValue: true,
          isInputValue: true,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e7f77ab8ec536409992de8",
          method: "UUID (Universally Unique Identifier)",
          isElementTarget: false,
          isOutputValue: true,
          isInputValue: true,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e7f77ab8ec536409992de9",
          method: "Generate OTP from Secret Key",
          isElementTarget: false,
          isOutputValue: true,
          isDeleted: false,
          isInputValue: true,
          subMethod: [],
        },
        {
          _id: "66e7f77ab8ec536409992dea",
          method: "Extract Value from Element",
          isElementTarget: true,
          isOutputValue: false,
          isInputValue: false,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e7f77ab8ec536409992deb",
          method: "Extract Value from Element with OCR",
          isElementTarget: true,
          isOutputValue: false,
          isDeleted: false,
          isInputValue: false,
          subMethod: [],
        },
        {
          _id: "66e7f77ab8ec536409992dec",
          method: "Extract Attribute from Element",
          isElementTarget: true,
          isOutputValue: false,
          isInputValue: false,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e7f77ab8ec536409992ded",
          method: "Extract CSS Property from Element",
          isElementTarget: true,
          isOutputValue: false,
          isDeleted: false,
          isInputValue: false,
          subMethod: [],
        },
        {
          _id: "66e7f77ab8ec536409992dee",
          method: "Extract Value from JavaScript Variable",
          isElementTarget: false,
          isOutputValue: false,
          isInputValue: true,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e7f77ab8ec536409992def",
          method: "Extract Value from Cookie",
          isElementTarget: false,
          isOutputValue: false,
          isInputValue: true,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e7f77ab8ec536409992df0",
          method: "Extract Value from Alert",
          isElementTarget: false,
          isOutputValue: false,
          isInputValue: false,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e7f77ab8ec536409992df1",
          method: "Extract CSS Selector from Focused Element",
          isElementTarget: false,
          isOutputValue: false,
          isInputValue: false,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e7f77ab8ec536409992df2",
          method: "Extract Result from SQL Query",
          isElementTarget: false,
          isOutputValue: false,
          isDeleted: false,
          isInputValue: false,
          subMethod: [],
        },
        {
          _id: "66e7f77ab8ec536409992df3",
          method: "Extract Latest SMS",
          isElementTarget: false,
          isInputValue: false,
          isOutputValue: false,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e7f77ab8ec536409992df4",
          method: "Extract Current URL",
          isElementTarget: false,
          isOutputValue: false,
          isInputValue: false,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e7f77ab8ec536409992df5",
          method: "Extract Current Title",
          isElementTarget: false,
          isOutputValue: false,
          isDeleted: false,
          isInputValue: false,
          subMethod: [],
        },
        {
          _id: "66e7f77ab8ec536409992df6",
          method: "Extract Number of Elements",
          isElementTarget: true,
          isOutputValue: false,
          isInputValue: false,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e7f77ab8ec536409992df7",
          method: "Extract Number of Child Elements",
          isElementTarget: true,
          isOutputValue: false,
          isInputValue: false,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e7f77ab8ec536409992df8",
          method: "Extract Name of Most Recent Downloaded File",
          isElementTarget: false,
          isOutputValue: false,
          isDeleted: false,
          isInputValue: false,
          subMethod: [],
        },
        {
          _id: "66e7f77ab8ec536409992df9",
          method: "Extract Size of Most Recent Downloaded File",
          isElementTarget: false,
          isOutputValue: false,
          isInputValue: false,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e7f77ab8ec536409992dfa",
          method: "Extract MIME Type of Most Recent Downloaded File",
          isElementTarget: false,
          isOutputValue: false,
          isInputValue: false,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e7f77ab8ec536409992dfb",
          method: "Link to Most Recent Downloaded File",
          isElementTarget: false,
          isOutputValue: false,
          isInputValue: false,
          isDeleted: false,
          subMethod: [],
        },
      ],
    },
    {
      _id: "66e7f974b8ec536409992e02",
      method: "Transfer to JavaScript",
      label: "Variable Name",
      subMethod: [
        {
          _id: "66e7f974b8ec536409992e03",
          method: "Variable",
          isElementTarget: false,
          isOutputValue: true,
          isInputValue: false,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e7f974b8ec536409992e04",
          method: "All variables",
          isElementTarget: false,
          isOutputValue: true,
          isInputValue: false,
          isDeleted: false,
          subMethod: [],
        },
      ],
    },
    {
      _id: "66e7fdeab8ec536409992e07",
      method: "Miscellaneous",
      label: "Miscellaneous Type",
      subMethod: [
        {
          _id: "66e7fdeab8ec536409992e08",
          method: "Hover",
          isElementTarget: true,
          isOutputValue: false,
          isInputValue: false,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e7fdeab8ec536409992e09",
          method: "Move Element by Offset",
          isElementTarget: true,
          isOutputValue: false,
          isInputValue: false,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e7fdeab8ec536409992e0a",
          method: "Move Target by Offset",
          isElementTarget: false,
          isOutputValue: false,
          isInputValue: true,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e7fdeab8ec536409992e0b",
          method: "Clear Input",
          isElementTarget: false,
          isOutputValue: false,
          isInputValue: true,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e7fdeab8ec536409992e0c",
          method: "Press Keys",
          isElementTarget: false,
          isOutputValue: false,
          isInputValue: false,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e7fdeab8ec536409992e0d",
          method: "Refresh Page",
          isElementTarget: false,
          isInputValue: false,
          isOutputValue: false,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e7fdeab8ec536409992e0e",
          method: "Go Back",
          isElementTarget: false,
          isOutputValue: false,
          isInputValue: false,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e7fdeab8ec536409992e0f",
          method: "Go Forward",
          isElementTarget: false,
          isOutputValue: false,
          isInputValue: false,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e7fdeab8ec536409992e10",
          method: "Wait Until",
          isDeleted: false,
          subMethod: [
            {
              _id: "66e7fdeab8ec536409992e11",
              method: "Element Is Present",
              isElementTarget: true,
              isOutputValue: false,
              isInputValue: false,
              isDeleted: false,
            },
            {
              _id: "66e7fdeab8ec536409992e12",
              method: "Element Is Not Present",
              isElementTarget: true,
              isOutputValue: false,
              isInputValue: false,
              isDeleted: false,
            },
            {
              _id: "66e7fdeab8ec536409992e13",
              method: "Element Is Visible",
              isElementTarget: true,
              isOutputValue: false,
              isInputValue: false,
              isDeleted: false,
            },
            {
              _id: "66e7fdeab8ec536409992e14",
              method: "Element Is Not Visible",
              isElementTarget: true,
              isOutputValue: false,
              isInputValue: false,
              isDeleted: false,
            },
            {
              _id: "66e7fdeab8ec536409992e15",
              method: "Element Is Clickable",
              isElementTarget: true,
              isOutputValue: false,
              isInputValue: false,
              isDeleted: false,
            },
            {
              _id: "66e7fdeab8ec536409992e16",
              method: "Element Is Not Clickable",
              isElementTarget: true,
              isOutputValue: false,
              isInputValue: false,
              isDeleted: false,
            },
            {
              _id: "66e7fdeab8ec536409992e17",
              method: "Element Matches Value",
              isElementTarget: true,
              isOutputValue: false,
              isInputValue: false,
              isDeleted: false,
            },
            {
              _id: "66e7fdeab8ec536409992e18",
              method: "Element Does Not Match Value",
              isElementTarget: true,
              isInputValue: false,
              isOutputValue: false,
              isDeleted: false,
            },
            {
              _id: "66e7fdeab8ec536409992e19",
              method: "Element Contains Value",
              isElementTarget: true,
              isInputValue: false,
              isOutputValue: false,
              isDeleted: false,
            },
            {
              _id: "66e7fdeab8ec536409992e1a",
              method: "Element Does Not Contain Value",
              isElementTarget: true,
              isOutputValue: false,
              isInputValue: false,
              isDeleted: false,
            },
            {
              _id: "66e7fdeab8ec536409992e1b",
              method: "Element Contains CSS Class",
              isElementTarget: true,
              isInputValue: false,
              isOutputValue: false,
              isDeleted: false,
            },
            {
              _id: "66e7fdeab8ec536409992e1c",
              method: "Element Does Not Contain CSS Class",
              isElementTarget: true,
              isOutputValue: false,
              isInputValue: false,
              isDeleted: false,
            },
            {
              _id: "66e7fdeab8ec536409992e1d",
              method: "Title Contains Value",
              isElementTarget: false,
              isInputValue: true,
              isOutputValue: false,
              isDeleted: false,
            },
            {
              _id: "66e7fdeab8ec536409992e1e",
              method: "Title Does Not Contain Value",
              isElementTarget: false,
              isInputValue: true,
              isOutputValue: false,
              isDeleted: false,
            },
            {
              _id: "66e7fdeab8ec536409992e1f",
              method: "URL Contains Value",
              isElementTarget: false,
              isOutputValue: false,
              isInputValue: true,
              isDeleted: false,
            },
            {
              _id: "66e7fdeab8ec536409992e20",
              method: "URL Does Not Contain Value",
              isElementTarget: false,
              isOutputValue: false,
              isInputValue: true,
              isDeleted: false,
            },
            {
              _id: "66e7fdeab8ec536409992e21",
              method: "Page Source Contains Value",
              isElementTarget: false,
              isOutputValue: false,
              isInputValue: true,
              isDeleted: false,
            },
            {
              _id: "66e7fdeab8ec536409992e22",
              method: "Page Source Does Not Contain Value",
              isElementTarget: false,
              isOutputValue: false,
              isInputValue: true,
              isDeleted: false,
            },
            {
              _id: "66e7fdeab8ec536409992e23",
              method: "Cookies Contain Value",
              isElementTarget: false,
              isInputValue: true,
              isOutputValue: false,
              isDeleted: false,
            },
            {
              _id: "66e7fdeab8ec536409992e24",
              method: "Cookies Do Not Contain Value",
              isElementTarget: false,
              isOutputValue: false,
              isInputValue: true,
              isDeleted: false,
            },
            {
              _id: "66e7fdeab8ec536409992e25",
              method: "Browser Logs Contain Value",
              isElementTarget: false,
              isOutputValue: false,
              isInputValue: true,
              isDeleted: false,
            },
            {
              _id: "66e7fdeab8ec536409992e26",
              method: "Browser Logs Do Not Contain Value",
              isElementTarget: false,
              isOutputValue: false,
              isInputValue: true,
              isDeleted: false,
            },
            {
              _id: "66e7fdeab8ec536409992e27",
              method: "Page Matches Screenshot",
              isElementTarget: false,
              isOutputValue: false,
              isInputValue: true,
              isDeleted: false,
            },
            {
              _id: "66e7fdeab8ec536409992e28",
              method: "Element Matches Screenshot",
              isElementTarget: true,
              isOutputValue: false,
              isInputValue: false,
              isDeleted: false,
            },
          ],
        },
        {
          _id: "66e7fdeab8ec536409992e29",
          method: "Switch to iframe",
          isElementTarget: true,
          isOutputValue: false,
          isInputValue: false,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e7fdeab8ec536409992e2a",
          method: "Switch back to main",
          isElementTarget: false,
          isInputValue: false,
          isOutputValue: false,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e7fdeab8ec536409992e2b",
          method: "Open new tab",
          isElementTarget: false,
          isInputValue: false,
          isOutputValue: false,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e7fdeab8ec536409992e2c",
          method: "Switch to next tab",
          isElementTarget: false,
          isOutputValue: false,
          isInputValue: false,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e7fdeab8ec536409992e2d",
          method: "Switch to previous tab",
          isElementTarget: false,
          isOutputValue: false,
          isDeleted: false,
          isInputValue: false,
          subMethod: [],
        },
        {
          _id: "66e7fdeab8ec536409992e2e",
          method: "Switch to Shadow DOM",
          isElementTarget: true,
          isOutputValue: false,
          isInputValue: false,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e7fdeab8ec536409992e2f",
          method: "Switch to main DOM",
          isElementTarget: false,
          isOutputValue: false,
          isInputValue: false,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e7fdeab8ec536409992e30",
          method: "Close tab",
          isElementTarget: false,
          isOutputValue: false,
          isInputValue: false,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e7fdeab8ec536409992e31",
          method: "Close alert",
          isElementTarget: false,
          isOutputValue: false,
          isInputValue: false,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e7fdeab8ec536409992e32",
          method: "Get Page Source",
          isElementTarget: false,
          isOutputValue: false,
          isDeleted: false,
          isInputValue: false,
          subMethod: [],
        },
        {
          _id: "66e7fdeab8ec536409992e33",
          method: "Get Cookies",
          isElementTarget: false,
          isOutputValue: false,
          isInputValue: false,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e7fdeab8ec536409992e34",
          method: "Delete Cookies",
          isElementTarget: false,
          isOutputValue: false,
          isInputValue: false,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e7fdeab8ec536409992e35",
          method: "Clear Local Storage",
          isElementTarget: false,
          isOutputValue: false,
          isInputValue: false,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e7fdeab8ec536409992e36",
          method: "Clear Session Storage",
          isElementTarget: false,
          isOutputValue: false,
          isDeleted: false,
          isInputValue: false,
          subMethod: [],
        },
        {
          _id: "66e7fdeab8ec536409992e37",
          method: "Clear API Session",
          isElementTarget: false,
          isOutputValue: false,
          isDeleted: false,
          isInputValue: false,
          subMethod: [],
        },
        {
          _id: "66e7fdeab8ec536409992e38",
          method: "Clear Browser Logs",
          isElementTarget: false,
          isOutputValue: false,
          isInputValue: false,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e7fdeab8ec536409992e39",
          method: "Generate Full Page Screenshot",
          isElementTarget: false,
          isOutputValue: false,
          isInputValue: false,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e7fdeab8ec536409992e3a",
          method: "Utilities",
          isDeleted: false,
          subMethod: [
            {
              _id: "66e7fdeab8ec536409992e3b",
              method: "Extract Text After Pattern",
              isElementTarget: false,
              isOutputValue: false,
              isInputValue: false,
              isDeleted: false,
            },
            {
              _id: "66e7fdeab8ec536409992e3c",
              method: "Extract Text Before Pattern",
              isElementTarget: false,
              isOutputValue: false,
              isInputValue: false,
              isDeleted: false,
            },
            {
              _id: "66e7fdeab8ec536409992e3d",
              method: "Extract Numbers From Text",
              isElementTarget: false,
              isInputValue: false,
              isOutputValue: false,
              isDeleted: false,
            },
            {
              _id: "66e7fdeab8ec536409992e3e",
              method: "Extract Value From JSON",
              isElementTarget: false,
              isInputValue: false,
              isOutputValue: false,
              isDeleted: false,
            },
            {
              _id: "66e7fdeab8ec536409992e3f",
              method: "Extract Value From XML",
              isElementTarget: false,
              isInputValue: false,
              isOutputValue: false,
              isDeleted: false,
            },
            {
              _id: "66e7fdeab8ec536409992e40",
              method: "Extract Item From Array",
              isElementTarget: false,
              isInputValue: false,
              isOutputValue: false,
              isDeleted: false,
            },
            {
              _id: "66e7fdeab8ec536409992e41",
              method: "Extract Last Item From Array",
              isElementTarget: false,
              isOutputValue: false,
              isInputValue: false,
              isDeleted: false,
            },
            {
              _id: "66e7fdeab8ec536409992e42",
              method: "Extract Random Item From List",
              isElementTarget: false,
              isOutputValue: false,
              isInputValue: false,
              isDeleted: false,
            },
            {
              _id: "66e7fdeab8ec536409992e43",
              method: "Get Text Length",
              isElementTarget: false,
              isOutputValue: false,
              isInputValue: false,
              isDeleted: false,
            },
            {
              _id: "66e7fdeab8ec536409992e44",
              method: "Get Array Length",
              isElementTarget: false,
              isOutputValue: false,
              isInputValue: false,
              isDeleted: false,
            },
            {
              _id: "66e7fdeab8ec536409992e45",
              method: "Store Item in Vault",
              isElementTarget: false,
              isOutputValue: false,
              isInputValue: false,
              isDeleted: false,
            },
            {
              _id: "66e7fdeab8ec536409992e46",
              method: "Get Item from Vault",
              isElementTarget: false,
              isInputValue: false,
              isOutputValue: false,
              isDeleted: false,
            },
            {
              _id: "66e7fdeab8ec536409992e47",
              method: "Generate Random Name",
              isElementTarget: false,
              isOutputValue: false,
              isInputValue: false,
              isDeleted: false,
            },
            {
              _id: "66e7fdeab8ec536409992e48",
              method: "Extract Character from String",
              isElementTarget: false,
              isInputValue: false,
              isOutputValue: false,
              isDeleted: false,
            },
            {
              _id: "66e7fdeab8ec536409992e49",
              method: "Convert Text to LowerCase",
              isElementTarget: false,
              isInputValue: false,
              isOutputValue: false,
              isDeleted: false,
            },
            {
              _id: "66e7fdeab8ec536409992e4a",
              method: "Convert Text to UpperCase",
              isElementTarget: false,
              isOutputValue: false,
              isInputValue: false,
              isDeleted: false,
            },
            {
              _id: "66e7fdeab8ec536409992e4b",
              method: "Capitalize Text",
              isElementTarget: false,
              isInputValue: false,
              isOutputValue: false,
              isDeleted: false,
            },
            {
              _id: "66e7fdeab8ec536409992e4c",
              method: "Remove All Spaces",
              isElementTarget: false,
              isOutputValue: false,
              isInputValue: false,
              isDeleted: false,
            },
            {
              _id: "66e7fdeab8ec536409992e4d",
              method: "Remove Pattern from Text",
              isElementTarget: false,
              isOutputValue: false,
              isInputValue: false,
              isDeleted: false,
            },
            {
              _id: "66e7fdeab8ec536409992e4e",
              method: "Math Calculations",
              isElementTarget: false,
              isOutputValue: false,
              isInputValue: false,
              isDeleted: false,
            },
            {
              _id: "66e7fdeab8ec536409992e4f",
              method: "Remove Newline Characters",
              isElementTarget: false,
              isInputValue: false,
              isOutputValue: false,
              isDeleted: false,
            },
            {
              _id: "66e7fdeab8ec536409992e50",
              method: "Send Email",
              isElementTarget: false,
              isInputValue: false,
              isOutputValue: false,
              isDeleted: false,
            },
            {
              _id: "66e7fdeab8ec536409992e51",
              method: "Trim String",
              isElementTarget: false,
              isOutputValue: false,
              isInputValue: false,
              isDeleted: false,
            },
          ],
        },
        {
          _id: "66e7fdeab8ec536409992e52",
          method: "Jump to Next Test Case",
          isElementTarget: false,
          isOutputValue: false,
          isInputValue: false,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e7fdeab8ec536409992e53",
          method: "Stop Test",
          isElementTarget: false,
          isOutputValue: false,
          isInputValue: false,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e7fdeab8ec536409992e54",
          method: "Clear Downloads Directory",
          isElementTarget: false,
          isInputValue: false,
          isOutputValue: false,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e7fdeab8ec536409992e55",
          method: "Write Text",
          isElementTarget: true,
          isInputValue: false,
          isOutputValue: false,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e7fdeab8ec536409992e56",
          method: "Go to URL",
          isElementTarget: false,
          isOutputValue: false,
          isInputValue: true,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e7fdeab8ec536409992e57",
          method: "Select Option",
          isElementTarget: false,
          isInputValue: false,
          isOutputValue: false,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e7fdeab8ec536409992e58",
          method: "Connect to Database",
          isElementTarget: false,
          isOutputValue: false,
          isInputValue: false,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e7fdeab8ec536409992e59",
          method: "Execute SQL Query",
          isElementTarget: false,
          isInputValue: false,
          isOutputValue: false,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e7fdeab8ec536409992e5a",
          method: "Set Window Size",
          isElementTarget: false,
          isOutputValue: false,
          isInputValue: false,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e7fdeab8ec536409992e5b",
          method: "Set Window Position",
          isElementTarget: false,
          isOutputValue: false,
          isInputValue: false,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e7fdeab8ec536409992e5c",
          method: "Maximize Window",
          isElementTarget: false,
          isOutputValue: false,
          isInputValue: false,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e7fdeab8ec536409992e5d",
          method: "Minimize Window",
          isElementTarget: false,
          isInputValue: false,
          isOutputValue: false,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e7fdeab8ec536409992e5e",
          method: "Screenshot Element",
          isElementTarget: true,
          isOutputValue: false,
          isInputValue: false,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e7fdeab8ec536409992e5f",
          method: "Upload File With Local Form",
          isElementTarget: true,
          isInputValue: true,
          isOutputValue: false,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e7fdeab8ec536409992e60",
          method: "Upload File With Send Keys",
          isElementTarget: true,
          isOutputValue: false,
          isInputValue: true,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e7fdeab8ec536409992e61",
          method: "Explicit Wait",
          isElementTarget: false,
          isOutputValue: false,
          isDeleted: false,
          isInputValue: true,
          subMethod: [],
        },
        {
          _id: "66e7fdeab8ec536409992e62",
          method: "Wait For Page Loaded",
          isElementTarget: false,
          isOutputValue: false,
          isInputValue: false,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e7fdeab8ec536409992e63",
          method: "Wait For Page To Load",
          isElementTarget: false,
          isOutputValue: false,
          isInputValue: false,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e7fdeab8ec536409992e64",
          method: "Wait For Page To Load",
          isElementTarget: false,
          isInputValue: false,
          isOutputValue: false,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e7fdeab8ec536409992e65",
          method: "Enter BackSpace",
          isElementTarget: false,
          isOutputValue: false,
          isInputValue: false,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e7fdeab8ec536409992e66",
          method: "HighLight Element",
          isElementTarget: true,
          isOutputValue: true,
          isInputValue: false,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e7fdeab8ec536409992e67",
          method: "Validate Element Text Equals",
          isElementTarget: true,
          isOutputValue: false,
          isInputValue: true,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e7fdeab8ec536409992e68",
          method: "Validate Element Text",
          isElementTarget: true,
          isOutputValue: false,
          isInputValue: true,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e7fdeab8ec536409992e69",
          method: "Validate Text From Ui",
          isElementTarget: true,
          isOutputValue: false,
          isInputValue: true,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e7fdeab8ec536409992e6a",
          method: "Validate Text Equals In List",
          isElementTarget: true,
          isOutputValue: false,
          isInputValue: true,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e7fdeab8ec536409992e6b",
          method: "Validate Text Equals In Map",
          isElementTarget: true,
          isOutputValue: false,
          isInputValue: true,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e7fdeab8ec536409992e6c",
          method: "Pdf Highlighter",
          isElementTarget: false,
          isOutputValue: false,
          isInputValue: true,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e7fdeab8ec536409992e6d",
          method: "Validate Text Element",
          isElementTarget: true,
          isOutputValue: false,
          isDeleted: false,
          isInputValue: true,
          subMethod: [],
        },
        {
          _id: "66e7fdeab8ec536409992e6e",
          method: "PDF Validation",
          isElementTarget: false,
          isOutputValue: false,
          isInputValue: true,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e7fdeab8ec536409992e6f",
          method: "Split With Space",
          isElementTarget: true,
          isOutputValue: true,
          isInputValue: true,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e7fdeab8ec536409992e70",
          method: "Set Text Using Actions",
          isElementTarget: true,
          isInputValue: true,
          isOutputValue: false,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e7fdeab8ec536409992e71",
          method: "Start Web Crawler",
          isElementTarget: false,
          isOutputValue: false,
          isDeleted: false,
          isInputValue: false,
          subMethod: [],
        },
        {
          _id: "66e7fdeab8ec536409992e72",
          method: "Send API Request",
          isElementTarget: false,
          isOutputValue: false,
          isInputValue: false,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e7fdeab8ec536409992e73",
          method: "Import Test Case",
          isElementTarget: false,
          isOutputValue: false,
          isInputValue: true,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e7fdeab8ec536409992e74",
          method: "Import Test Case Multiple Times",
          isElementTarget: false,
          isOutputValue: false,
          isInputValue: false,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e7fdeab8ec536409992e75",
          method: "Pause",
          isInputValue: true,
          isElementTarget: false,
          isOutputValue: false,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e7fdeab8ec536409992e76",
          method: "Take Screenshot",
          isElementTarget: false,
          isInputValue: false,
          isOutputValue: false,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e7fdeab8ec536409992e77",
          method: "Snipping Tool",
          isElementTarget: false,
          isOutputValue: false,
          isInputValue: false,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e7fdeab8ec536409992e78",
          method: "Upload File",
          isElementTarget: false,
          isOutputValue: false,
          isInputValue: false,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e7fdeab8ec536409992e79",
          method: "Press Key",
          isElementTarget: true,
          isOutputValue: false,
          isInputValue: false,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e7fdeab8ec536409992e7a",
          method: "Execute JavaScript",
          isElementTarget: false,
          isOutputValue: false,
          isInputValue: false,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e7fdeab8ec536409992e7b",
          method: "Import Test Case Multiple Times (CSV)",
          isElementTarget: false,
          isOutputValue: false,
          isInputValue: false,
          isDeleted: false,
          subMethod: [],
        },
      ],
    },
    {
      _id: "66e7fec4b8ec536409992e82",
      method: "Set Advanced Action",
      label: "Advanced Action Name",
      subMethod: [
        {
          _id: "66e7fec4b8ec536409992e83",
          method: "Drag element",
          isElementTarget: true,
          isInputValue: false,
          isOutputValue: false,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e7fec4b8ec536409992e84",
          method: "Drop on target",
          isElementTarget: true,
          isOutputValue: false,
          isInputValue: false,
          isDeleted: false,
          subMethod: [],
        },
      ],
    },
    {
      _id: "66e803b2b8ec536409992e88",
      method: "If Else Statements",
      label: "If Condition Type",
      subMethod: [
        {
          _id: "66e803b2b8ec536409992e89",
          method: "Element Is Present",
          isElementTarget: true,
          isOutputValue: false,
          isInputValue: false,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e803b2b8ec536409992e8a",
          method: "Element Is Not Present",
          isElementTarget: true,
          isOutputValue: false,
          isInputValue: false,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e803b2b8ec536409992e8b",
          method: "Element Is Visible",
          isElementTarget: true,
          isInputValue: false,
          isOutputValue: false,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e803b2b8ec536409992e8c",
          method: "Element Is Not Visible",
          isElementTarget: true,
          isOutputValue: false,
          isInputValue: false,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e803b2b8ec536409992e8d",
          method: "Element Is Clickable",
          isElementTarget: true,
          isOutputValue: false,
          isDeleted: false,
          isInputValue: false,
          subMethod: [],
        },
        {
          _id: "66e803b2b8ec536409992e8e",
          method: "Element Is Not Clickable",
          isElementTarget: true,
          isOutputValue: false,
          isInputValue: false,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e803b2b8ec536409992e8f",
          method: "Element Matches Value",
          isElementTarget: true,
          isOutputValue: false,
          isInputValue: false,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e803b2b8ec536409992e90",
          method: "Element Does Not Match Value",
          isElementTarget: true,
          isOutputValue: false,
          isInputValue: false,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e803b2b8ec536409992e91",
          method: "Element Contains Value",
          isElementTarget: true,
          isOutputValue: false,
          isInputValue: false,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e803b2b8ec536409992e92",
          method: "Element Does Not Contain Value",
          isElementTarget: true,
          isOutputValue: false,
          isInputValue: false,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e803b2b8ec536409992e93",
          method: "Element Contains CSS Class",
          isElementTarget: true,
          isOutputValue: false,
          isInputValue: false,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e803b2b8ec536409992e94",
          method: "Element Does Not Contain CSS Class",
          isElementTarget: true,
          isOutputValue: false,
          isInputValue: false,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e803b2b8ec536409992e95",
          method: "Element Contains Attribute",
          isElementTarget: true,
          isOutputValue: false,
          isInputValue: false,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e803b2b8ec536409992e96",
          method: "Element Does Not Contain Attribute",
          isElementTarget: true,
          isOutputValue: false,
          isInputValue: false,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e803b2b8ec536409992e97",
          method: "Count Child Elements",
          isElementTarget: true,
          isOutputValue: false,
          isInputValue: false,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e803b2b8ec536409992e98",
          method: "Variable Condition",
          isDeleted: false,
          subMethod: [
            {
              _id: "66e803b2b8ec536409992e99",
              method: "Variable Matches Value",
              isElementTarget: false,
              isOutputValue: true,
              isInputValue: true,
              isDeleted: false,
            },
            {
              _id: "66e803b2b8ec536409992e9a",
              method: "Variable Does Not Match Value",
              isElementTarget: false,
              isOutputValue: true,
              isInputValue: true,
              isDeleted: false,
            },
            {
              _id: "66e803b2b8ec536409992e9b",
              method: "Variable Contains Value",
              isElementTarget: false,
              isOutputValue: true,
              isInputValue: true,
              isDeleted: false,
            },
            {
              _id: "66e803b2b8ec536409992e9c",
              method: "Variable Does Not Contain Value",
              isElementTarget: false,
              isInputValue: true,
              isOutputValue: true,
              isDeleted: false,
            },
            {
              _id: "66e803b2b8ec536409992e9d",
              method: "Variable Starts With Value",
              isElementTarget: false,
              isOutputValue: true,
              isInputValue: true,
              isDeleted: false,
            },
            {
              _id: "66e803b2b8ec536409992e9e",
              method: "Variable Does Not Start With Value",
              isElementTarget: false,
              isInputValue: true,
              isOutputValue: true,
              isDeleted: false,
            },
            {
              _id: "66e803b2b8ec536409992e9f",
              method: "Variable Ends With Value",
              isElementTarget: false,
              isOutputValue: true,
              isInputValue: true,
              isDeleted: false,
            },
            {
              _id: "66e803b2b8ec536409992ea0",
              method: "Variable Does Not End With Value",
              isElementTarget: false,
              isOutputValue: true,
              isInputValue: true,
              isDeleted: false,
            },
            {
              _id: "66e803b2b8ec536409992ea1",
              method: "Variable Is Greater Than Value",
              isElementTarget: false,
              isInputValue: true,
              isOutputValue: true,
              isDeleted: false,
            },
            {
              _id: "66e803b2b8ec536409992ea2",
              method: "Variable Is Greater Than Or Equals Value",
              isElementTarget: false,
              isInputValue: true,
              isOutputValue: true,
              isDeleted: false,
            },
            {
              _id: "66e803b2b8ec536409992ea3",
              method: "Variable Is Less Than Value",
              isElementTarget: false,
              isOutputValue: true,
              isInputValue: true,
              isDeleted: false,
            },
            {
              _id: "66e803b2b8ec536409992ea4",
              method: "Variable Is Less Than Or Equals Value",
              isElementTarget: false,
              isOutputValue: true,
              isInputValue: true,
              isDeleted: false,
            },
            {
              _id: "66e803b2b8ec536409992ea5",
              method: "Variable Is Defined",
              isElementTarget: false,
              isOutputValue: false,
              isInputValue: true,
              isDeleted: false,
            },
            {
              _id: "66e803b2b8ec536409992ea6",
              method: "Variable Is Not Defined",
              isElementTarget: false,
              isInputValue: true,
              isOutputValue: false,
              isDeleted: false,
            },
            {
              _id: "66e803b2b8ec536409992ea7",
              method: "Variable Is Empty",
              isElementTarget: false,
              isOutputValue: false,
              isInputValue: true,
              isDeleted: false,
            },
            {
              _id: "66e803b2b8ec536409992ea8",
              method: "Variable Is Not Empty",
              isElementTarget: false,
              isInputValue: true,
              isOutputValue: false,
              isDeleted: false,
            },
            {
              _id: "66e803b2b8ec536409992ea9",
              method: "Variable Contains Numbers",
              isElementTarget: false,
              isOutputValue: false,
              isInputValue: true,
              isDeleted: false,
            },
            {
              _id: "66e803b2b8ec536409992eaa",
              method: "Variable Does Not Contain Numbers",
              isElementTarget: false,
              isInputValue: true,
              isOutputValue: false,
              isDeleted: false,
            },
          ],
        },
        {
          _id: "66e803b2b8ec536409992eab",
          method: "Title Contains Value",
          isElementTarget: false,
          isOutputValue: false,
          isInputValue: true,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e803b2b8ec536409992eac",
          method: "Title Does Not Contain Value",
          isElementTarget: false,
          isOutputValue: false,
          isInputValue: true,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e803b2b8ec536409992ead",
          method: "URL Contains Value",
          isElementTarget: false,
          isOutputValue: false,
          isInputValue: true,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e803b2b8ec536409992eae",
          method: "URL Does Not Contain Value",
          isElementTarget: false,
          isInputValue: true,
          isOutputValue: false,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e803b2b8ec536409992eaf",
          method: "Page Source Contains Value",
          isElementTarget: false,
          isOutputValue: false,
          isInputValue: true,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e803b2b8ec536409992eb0",
          method: "Page Source Does Not Contain Value",
          isElementTarget: false,
          isOutputValue: false,
          isInputValue: true,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e803b2b8ec536409992eb1",
          method: "Cookies Contain Value",
          isElementTarget: false,
          isInputValue: true,
          isOutputValue: false,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e803b2b8ec536409992eb2",
          method: "Cookies Do Not Contain Value",
          isElementTarget: false,
          isOutputValue: false,
          isDeleted: false,
          isInputValue: true,
          subMethod: [],
        },
        {
          _id: "66e803b2b8ec536409992eb3",
          method: "Browser Logs Contain Value",
          isElementTarget: false,
          isOutputValue: false,
          isDeleted: false,
          isInputValue: true,
          subMethod: [],
        },
        {
          _id: "66e803b2b8ec536409992eb4",
          method: "Browser Logs Do Not Contain Value",
          isElementTarget: false,
          isOutputValue: false,
          isInputValue: true,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e803b2b8ec536409992eb5",
          method: "Page Matches Screenshot",
          isElementTarget: false,
          isInputValue: true,
          isOutputValue: false,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e803b2b8ec536409992eb6",
          method: "Element Matches Screenshot",
          isElementTarget: true,
          isOutputValue: false,
          isInputValue: false,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e803b2b8ec536409992eb7",
          method: "End If Statement",
          isElementTarget: false,
          isOutputValue: false,
          isDeleted: false,
          isInputValue: false,
          subMethod: [],
        },
        {
          _id: "66e803b2b8ec536409992eb8",
          method: "Start Else Statement",
          isElementTarget: false,
          isInputValue: false,
          isOutputValue: false,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e803b2b8ec536409992eb9",
          method: "End Else Statement",
          isElementTarget: false,
          isInputValue: false,
          isOutputValue: false,
          isDeleted: false,
          subMethod: [],
        },
      ],
    },
    {
      _id: "66e93605f6bd428a88251989",
      method: "Click",
      label: "Click Type",
      subMethod: [
        {
          _id: "66e93605f6bd428a8825198a",
          method: "Click Element With Dynamic Locator",
          isElementTarget: true,
          isOutputValue: false,
          isDeleted: false,
          isInputValue: false,
          subMethod: [],
        },
        {
          _id: "66e93605f6bd428a8825198b",
          method: "Right Click",
          isElementTarget: true,
          isOutputValue: false,
          isInputValue: false,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e93605f6bd428a8825198c",
          method: "Double Click",
          isElementTarget: true,
          isOutputValue: false,
          isInputValue: false,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e93605f6bd428a8825198d",
          method: "Click with Offset",
          isElementTarget: false,
          isOutputValue: false,
          isInputValue: false,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e93605f6bd428a8825198e",
          method: "Right Click with Offset",
          isElementTarget: false,
          isOutputValue: false,
          isDeleted: false,
          isInputValue: false,
          subMethod: [],
        },
        {
          _id: "66e93605f6bd428a8825198f",
          method: "Double Click with Offset",
          isElementTarget: false,
          isOutputValue: false,
          isInputValue: false,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e93605f6bd428a88251990",
          method: "Click BackSpace",
          isElementTarget: false,
          isOutputValue: false,
          isInputValue: false,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e93605f6bd428a88251991",
          method: "Click Element",
          isElementTarget: true,
          isOutputValue: false,
          isDeleted: false,
          isInputValue: false,
          subMethod: [],
        },
        {
          _id: "66e93605f6bd428a88251992",
          method: "Click Element With Js",
          isElementTarget: true,
          isInputValue: false,
          isOutputValue: false,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e93605f6bd428a88251993",
          method: "Click Link Text",
          isElementTarget: true,
          isOutputValue: false,
          isInputValue: true,
          isDeleted: false,
          subMethod: [],
        },
        {
          _id: "66e93605f6bd428a88251994",
          method: "Click Enter",
          isElementTarget: false,
          isOutputValue: false,
          isInputValue: false,
          isDeleted: false,
          subMethod: [],
        },
      ],
    },
    {
      _id: "66e965dde9be058554689dc1",
      method: "Main Method",
      label: "main method",
      subMethod: [
        {
          _id: "66e965dde9be058554689dc2",
          method: "sub method one",
          isDeleted: false,
          subMethod: [
            {
              _id: "66e965dde9be058554689dc3",
              method: "updated method name",
              isElementTarget: false,
              isOutputValue: true,
              isDeleted: false,
            },
          ],
        },
      ],
    },
  ];